# Generated by Django 3.0.4 on 2020-03-10 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0003_movie_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
    ]
