# Generated by Django 3.0.4 on 2020-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0004_remove_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
    ]
