# Generated by Django 3.0.4 on 2020-03-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0005_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='movie',
            name='sub_type',
            field=models.CharField(choices=[(0, 'unknown'), (1, 'free'), (2, 'paid')], max_length=36, null=True),
        ),
    ]
