# Generated by Django 3.0.4 on 2020-03-10 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0006_auto_20200310_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='sub_type',
            new_name='subscription_type',
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='published_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
