# Generated by Django 3.0.4 on 2020-03-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0008_movie_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subscription_type',
        ),
    ]
