# Generated by Django 3.0.4 on 2020-03-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0009_remove_movie_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='published_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
