# Generated by Django 3.0.4 on 2020-03-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0010_auto_20200310_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subscription_type',
            field=models.CharField(choices=[(0, 'unknown'), (1, 'free'), (2, 'paid')], default=1, max_length=2),
        ),
    ]
