# Generated by Django 3.0.4 on 2020-03-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0011_movie_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='subscription_type',
            field=models.CharField(choices=[('UNKNOWN', 'unknown'), ('FREE', 'free'), ('PAID', 'paid')], max_length=9),
        ),
    ]
